### ISSUE TITLE
19 April 2023 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#130]
## Date
19 April 2023 - 2:00 PM GMT / 9:00 AM EST

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] We have search on osr.finos.org - @robmoffat 
- [x] Please do vote on #118 items!
- [x] Managing your Open Source based project - Taking your OSS contributions to the next level w/ @BrittanyIstenes - #132 
- [x] Software Inventory #128 w/ @robmoffat 
- [x] Discussion about #102 w/ @jstclair2019 
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by robmoffat** [comment]
Rob @ FINOS 🍇

**Comment by gyehuda** [comment]
Gil is here (and he works at U.S. Bank)

**Comment by BrittanyIstenes** [comment]
Brittany Istenes - FNMA

**Comment by rhyddian** [comment]
Rhyddian @ Citi 👋

**Comment by HelloKay27** [comment]
Kay XiongPachay / Goldman Sachs

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by robmoffat** [comment]
## Brittany’s doc: Leveraging your community
Kay: 
Including in the process, before starting the project, taking a look at IPs and patents.  There’s a big assumption that they can’t.  Patentability.
What are the pros and cons of contributing to a foundation?  

RM: 
There’s a budgetary component to this too.
From a banking perspective?  What happens then? 
BI: 
Happy to collaborate on someone with that to work out how to take this to the next level and add corporate angle.
Kay:
I’ll help with this. 
Important to know how to scale and how to maintain, and communicate with the community effectively.
BI: 
We should do the same for the other article from last time too

Thomas Cooper:
Online hackathons (hacktoberfest), allowing people to enter and lower barriers to entry.  
BI: 
That’s covered in the maintainership doc, but we should add that in here.

Thomas Cooper:
Our OSPO is organised… we have a developer advocacy function which coincides with OSS/InnerSource.  What are people’s thoughts on community managers wearing both hats.  Community Advocacy within the firm.  
BI:
It’d be great to have a guide for developer advocacy within a company.

TC:
Understanding where open source makes sense == developer advocacy.
We’re early in the journey.

Gill Yehuda:
One thing to add is to frame from: “here’s what we don’t mean - drive by contributions.. They might be tackling a problem already.  _Don’t_ do this.  Or, _this_ is outside the scope of the OSPO.  Corporate contribution vs. personal contribution guidelines. OSPO: why are you asking us?  This is nothing to do with work!”  Can we delineate that - it varies company to company.  
RO:
That’s exactly how we’re running it.  We’re explicit in training about the difference.  It ties into advocacy.  OSS contribution can be daunting.  The training / culture / advocacy part is coaching people through the first contributions.   They’ll come to us because they’re thinking about doing something but not sure - we coach on CLAs, DCOs.
BI:
Love the idea of what you “shouldn’t” do.  
Education should be a bullet on here.  
We’ll build on from a firm’s perspective and get Gill to help for what not to do.  
Karin Wolok?  Is a powerhouse community manager.  She knows tips and tricks about this.   

## Rob Moffat: Software Inventory (+Mark Hoare's Input)

Level 2 of the OSMM 
Need to understand what software you have in production, being built, etc..
SBOM? 

### Shift Left Concept 
- As project is getting built, more advancement will be happening 
- Leveraging the failure concepts within the model 
- Understanding your dependencies based on all libraries within your project 

### Tools 
- Spoke with folks at GitHub 
- Dependabot - easily configurable within GitHub orgs and repos 
- Artifactory and Nexus 

RO - OpenSSF?  Potentially reference them before building out this part 
RM - Reference article pointing to the other spaces that have these docs more matured
TC - Pain point to actually know what is out there - Backstage 
MF: is this about all software or just open source?
RO:  this should be all software. When you’re buying vendor products, many large organisations the contract specifies full disclosure over what is used.
RM: SBOMs are leading this way.  INventory is the base of the ptamid.
KX: Collaboration with tech risk.  
TC:  Tech governance plays a big role in defining what a good path is, and building out the inventory from there.
