### ISSUE TITLE
17 May 2023 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#142]
## Date
17 May 2023 - 9am EST / 2pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [ ] Convene & roll call (5mins)
- [ ] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [ ] Review Meeting Notices (see above)
- [ ] Approve past meeting minutes
- [ ] Added contributors to about page - #133 
- [ ] Discussion about Culture w/ @robmoffat  #140 
- [ ] Discussion about Policy and Why Open Source w/ @psmulovics #138 , #141 
- [ ] ...
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by caradelia** [comment]
👋 Cara Delia / Red Hat

**Comment by HelloKay27** [comment]
Kay XiongPachay / Goldman Sachs

**Comment by mimiflynn** [comment]
Mimi Flynn / Morgan Stanley

**Comment by rhyddian** [comment]
Rhyddian Olds @ Citi 👋

**Comment by robmoffat** [comment]
Agenda Item: 

1. Please add your bio image. Images taken from LI but let us know if you are not ok with. 
[PR](https://github.com/finos/open-source-readiness/pull/133)

2. Agenda Item: [Peter] Added content to BoK  [Update Policy](https://github.com/finos/open-source-readiness/pull/138) and [Why Contribute](https://github.com/finos/open-source-readiness/pull/141)> Why companies should start open source projects not just contribute to bug fixes, etc


    Feedback:


    [Gil] Fix common verbs “going” “contribute” associated with existing projects. For consistency, use the verb that implies publishing (implying new).


    [Rhyddian] when you start building ecosystems on top of open source software, then it is good to know the open 


    [Rhyddian] leveraging ecosystems - you can co-opt existing communities when you build functionality on top of existing projects

    [Katrina] Employees already contributing but no official process so happening offline


    [Tom] Make the right rules and formalized. Problem in German industries as seen as work.  If employees write code at night, then they might get into trouble with labor laws which say people can only work 10 hours a day

3. Agenda Item: [Rob] Level 3 contribution: [PR](https://github.com/finos/open-source-readiness/pull/135)

* New regulations section broken out but
* Describing you can sell the idea of open source to make your risk position better than before
* Differentiator
* Can set the direction if you are leading

    Feedback:


    [Tom] Clarify and define on social media vs communications vs collaboration tools


    [Rhyddian] how open source works within _each given policy - _how does the wording of each other policy apply to the open source policy? Work of setting OSS policy is about clarifying the applicability with the other policy owners.


    [Gil] regulators asking how collaboration outside the firm things happen at home based on collaboration tools- IP issue, policy issue


    [Tom] Open source, while free still has an IP value and therefore requires a tax in Dutch.Donating to LF by giving to a non-profit, they denounce ownership and to cover not needing to tax because of a neutral 3rd party that has governance.  This is then seen as donating to charity.


    [RobU]- OTOH, in the US, it would be easy for employers to assert IP ownership over employees contributions.


    [Gil] - however, the fact that there is then IP outside the company means that they’re in breach of _another _policy.  This is an unintended consequence.  It’s easier to pretend you don’t know about it.


    [RobU] - yes, don’t ask don’t tell


    [Rhyddian] - this is why policies aren’t explicit and talk in generalities.


    [Tom] - in Europe, it’s harder to sue and more about labor laws.  Example of Volkswagen writing software used by Porsche.  This is “influence” and goes against regulations.  Easier to donate to the LF to get around this.  What about **Cartel Law?** This should be covered too.


    [PeterS] This also applies to banking, we can find examples there of subsidiaries formed to sell commodities or whatever.


    [RobU] - please fix reference to “Chinese Walls”


    [RobU] - GitHub can be surveilled, which means that it is acceptable from a social media perspective.  Email, Symphony, Zoom also.  Slack would not be allowed and therefore isn’t like the other things.  What about mentioning a PR on Twitter?


    [RobU] Big debate around GitHub IDs and whether it’s about email addresses.  (To be covered next time)
