### ISSUE TITLE
5 December 2023 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#222]
## Date
5 December 2023 - 10 am EST / 3 pm GMT

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://community.finos.org/docs/governance/meeting-procedures/). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://community.finos.org/docs/finos-maintainers-cheatsheet).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://community.finos.org/docs/governance/code-of-conduct) and all other [FINOS policies](https://community.finos.org/docs/governance/#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene & roll call (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://community.finos.org/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes
- [x] Foundation PR with @BrittanyIstenes #159 
- [x] Maturity checklist demo from @robmoffat 
- [ ] Theming of the site with @mimiflynn and @robmoffat #204 
- [x] Is BoK a good name? with @robmoffat , @BrittanyIstenes #204  
- [x] The new front page with @robmoffat #201 
- [x] InnerSource portal merge #221 
- [ ] AOB, Q&A & Adjourn (5mins)

## Decisions Made
- [ ] Decision 1
- [ ] Decision 2
- [ ] ...

## Action Items
- [ ] Action 1
- [ ] Action 2
- [ ] ...

### Zoom Details
- https://zoom.us/j/99753528440?pwd=OEFPWkQzLy9hWlV4NmM0RC9VRjhwQT09
- **Meeting ID:** 997 5352 8440
- **Passcode:** 987996

### Join by Phone
- Find your local number: https://zoom.us/u/adl5rhui4P

**Comment by BrittanyIstenes** [comment]
Brittany Istenes - FNMA

**Comment by psmulovics** [comment]
Peter Smulovics / Morgan Stanley

**Comment by robmoffat** [comment]
Rob Moffat / FINOS 🏹

**Comment by eminty69** [comment]
Elspeth Minty / RBC

**Comment by robmoffat** [comment]
### Foundations: (BI)



* Difference in modus.  Needs Thomas’ help to move this along.  
* Wants to write an FAQ for foundations - added to the work for next year.
* RM - can Mao answer questions about transferring logos etc?  
* RM / BI / PS - discussed remaining edits.  
* PS - I was good with it.
* Group agreed to merge 


### Maturity Checklist (RM)



* RM demonstrated the checklist
* PS - there is a library to generate PDF on the client side.
* EM - do we want to do same with inner source model?
* BI - we can refresh it and use it.
* RM- we should use this in multiple areas - inner source too
* VL - for level 5, more and more a maturity model is focusing on business value and strategy.  One reason is open source is generic, not specific. But FINOS, it should be possible to identify the strategy.  This should be on the agenda for most executives.  We can add information to the 5 levels. We should 
* BI - Love that!  "What is the End Goal" and how to leverage your C- Suite
* VL - I started some work to research what is going on in the industry.  Nowhere in the FINOS website about open banking.  That’s one area.  The question is how do banks survive in next 10 years?  Secret sauce is often only known by a few people.
* BI - can we get some c-suite people here to talk to them on this?
* VL - FINOS are in a good position to do this.   We can create something based on public information.  We can publish our ideas, FINOS can talk about those strategies.  Top execs might join to talk about 
* RM - open banking is an example of the “open source standards” strategy - the british government implemented this strategy very successfully and now others are doing it. 
* VL - it’s not only open source, it’s about sharing customer data. For the innovation to happen, customer data has to be available through APIs.  How can that be done? Implementations are very fragmented at the moment.  A lot of big banks look at this regulation but don’t know technical details.  This could be a good FINOS project. 
* VL - there’s also open source AI.  Code. Data.  Existing channels 
* RM - finos does try to address this through strategic initiatives.  We will be choosing the ones for 2024 soon.
* VL - the model is always evolving.  This is true on CNCF.  We need a dynamic community with c-level involvement.
* BI - this is a wide topic.  I’m thinking we should hold a special SIG meeting with this as a core topic.  We could ask people to talk about Open Banking, C-Suite maturity model.  We could get input on these things and then disseminate out the work.
* **VL: Create a powerpoint presentation for discussion in this session.**
* **RM - 7th January will be our special session then.**


### Naming the Site



* RM: I’m thinking we use the original urls, osr and innersource, and point them to different parts of the site.
* RM talking with Brittany the other week, we should have 5 or 6 landing pages which take you through the details of that topic and lead onto the main taxonomic structure.
* **RM - will build a mock up of this structure for people to have a play with**
* BI - this is a quarter’s worth of work right there.


### Next Meeting:

* OSR - 17th January
