### ISSUE TITLE
Strategy Page

### ISSUE THREAD

**Issue by robmoffat** [finos/open-source-readiness#233]
### Description of Problem:
This is currently a placeholder:  https://osr.finos.org/Strategy

### Potential Solutions:

Would be nice to fill this out.  We could have a tag within the projects say "Strategy Frontpage" and show all the docs tagged with that.   

But further html/text introducing the topic would be good.

On 7th Feb Victor Lu is doing an OSR session on Strategy and Maturity which we can export and render onto the osr site too. This contains some useful info.

```[tasklist]
### Tasks
- [ ] Add boilerplate text to the page
- [x] Add a way to collect articles with the tag and display
- [x] Add Victor's deck to Presentations
```
