### ISSUE TITLE
04 May 2022 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by psmulovics** [finos/open-source-readiness#31]
## Date
04 May 2022 - 3pm UK / 10am ET

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] Approve past meeting minutes: #20 , #24 , #26 
- [x] Reminder of today's https://github.com/finos/community/issues/183
- [x] [VMB presenting about the move of OSSM into FINOS labs](https://github.com/finos/open-source-readiness/issues/26#issuecomment-1086217213)
- [x] Review [OSR Project board](https://github.com/orgs/finos/projects/28)
- [x] Gather info/use cases for #34 
- [ ] (if time remains) Gather info/use cases for #35 
- [x] AOB, Q&A & Adjourn (5mins)

## Minutes
- FINOS / Wipro working on the Open Source Maturity Model
- OSMM has been moved to FINOS Labs. This is where development will take place 
  - https://github.com/finos-labs/osmm
- OSMM Version 2.0 development in progress.
- OSMM Issues can be opened on FINOS Labs.
- OSR reviewed the SIG kanban
- SIG Roadmap invites comments from the OSR community 
  - https://github.com/finos/open-source-readiness/pull/29
- SIG community welcome to add items to the GitHub issues.
- Review of https://github.com/finos/open-source-readiness/issues/34 
- Details given by various members of the OSR community 
  - [ ] @psmulovics / @vmbrasseur please confirm this conversation has been used in the production of OSR content

### WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

**Comment by bingenito** [comment]
Brian / Morgan Stanley

**Comment by vmbrasseur** [comment]
VMB / Wipro

**Comment by robmoffat** [comment]
Rob / FINOS

**Comment by mcleo-d** [comment]
Hi everyone 👋🏻

**Comment by gahuja** [comment]
Hello everyone.

**Comment by djohnston89** [comment]
Hello everyone! David Johnston- Red Hat

**Comment by vmbrasseur** [comment]
👋🤠
