### ISSUE TITLE
03 Aug 2022 - Open Source Readiness Meeting Agenda

### ISSUE THREAD

**Issue by vmbrasseur** [finos/open-source-readiness#48]
## Date
2022-08-03 - 3pm UK / 10am ET

## Untracked attendees
- Fullname, Affiliation, (optional) GitHub username
- ...

## Meeting notices
- FINOS **Project leads** are responsible for observing the FINOS guidelines for [running project meetings](https://github.com/finos/community/blob/master/governance/Meeting-Procedures.md#run-the-meeting). Project maintainers can find additional resources in the [FINOS Maintainers Cheatsheet](https://odp.finos.org/docs/finos-maintainers-cheatsheet/).

- **All participants** in FINOS project meetings are subject to the [LF Antitrust Policy](https://www.linuxfoundation.org/antitrust-policy/), the [FINOS Community Code of Conduct](https://github.com/finos/community/blob/master/governance/Code-of-Conduct.md) and all other [FINOS policies](https://github.com/finos/community/tree/master/governance#policies). 

- FINOS meetings involve participation by industry competitors, and it is the intention of FINOS and the Linux Foundation to conduct all of its activities in accordance with applicable antitrust and competition laws. It is therefore extremely important that attendees adhere to meeting agendas, and be aware of, and not participate in, any activities that are prohibited under applicable US state, federal or foreign antitrust and competition laws. Please contact legal@finos.org with any questions.

- FINOS project meetings may be recorded for use solely by the FINOS team for administration purposes. In very limited instances, and with explicit approval, recordings may be made more widely available.

## Agenda
- [x] Convene (5mins)
- [x] Display [FINOS Antitrust Policy summary slide](https://github.com/finos/community/blob/master/governance/Compliance-Slides/Antitrust-Compliance-Slide.pdf) 
- [x] Review Meeting Notices (see above)
- [x] [Rhyddian/Citi][git-proxy](https://github.com/finos/git-proxy) update & demo
- [x] Approve past meeting minutes: #39 , #45 
- [x] State of Open Source in Finance Survey: https://www.research.net/r/PNBKH9W
- [x] [Peter] FYI: New OSR microsite page (from #47)
- [x] [VMB] FYI: New PR to review (#50 )
- [x] [Rob] FINOS London: Recap of the Finserv OSPO Round table
- [x] AOB, Q&A & Adjourn (5mins)

### WebEx info
- Webex: https://finos.webex.com/finos/j.php?MTID=mec6bb47084d671bc772c0652add2605c
- Meeting number: 664 434 054

### Join by phone
- +1-415-655-0003 US Toll
- +44-20319-88141 UK Toll
- Access code: 664 434 054

**Comment by Julia-Ritter** [comment]
Proposed agenda topic:

- 2022 State of [Open Source in Financial Services Survey](https://www.linuxfoundation.org/featured/finos-announces-2022-state-of-open-source-in-financial-services-survey/)

Please participate as soon as possible, as we intend to close the survey in early August!

**Comment by vmbrasseur** [comment]
> Proposed agenda topic:
> 
> * 2022 State of [Open Source in Financial Services Survey](https://www.linuxfoundation.org/featured/finos-announces-2022-state-of-open-source-in-financial-services-survey/)
> 
> Please participate as soon as possible, as we intend to close the survey in early August!

It's already listed in the agenda, too!

**Comment by pholleran** [comment]
👋

**Comment by psmulovics** [comment]
Peter Smulovics, Morgan Stanley, OSR co-chair

**Comment by vmbrasseur** [comment]
Hello there! Here's my attendance comment.

**Comment by Julia-Ritter** [comment]
Julia / FINOS

**Comment by chamindra** [comment]
Chamindra De Silva, Citi 👋

**Comment by bingenito** [comment]
Brian Ingenito / Morgan Stanley

**Comment by jgavronsky** [comment]
Jane / FINOS

**Comment by abacaphiliac** [comment]
Tim / Amex

**Comment by Julia-Ritter** [comment]
**Untracked attendees:**



Brian Ingenito / Morgan Stanley 
Paul Groves / Citi
Katrina Novakovic / Citi
Elspeth Minty / RBC
Girish Ahuja / jri-america
Hugo Cantave / GSHI
Avi / SocGen

**Comment by vmbrasseur** [comment]
@Julia-Ritter Do you have notes from this meeting?

**Comment by robmoffat** [comment]
can this be closed now?
